version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/main.go
  postgres:
    cmds:
      - docker run --name postgres -p 5432:5432 -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -d ubuntu/postgres
  createdb:
    cmds:
      - docker exec -it postgres createdb --username=user --owner=user jpsdb
      